version: "3"
services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    stop_grace_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d
      - ./var/lib/mysql:/var/lib/mysql
  php:
    image: juampynr/d8workflow:latest
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/root/.ssh
